# Generated by Django 2.1.10 on 2020-08-24 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonstocktransactionrecord',
            name='PhotoLink',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='PhotoLink',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='SerialNumber',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9- ]+$')]),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='TicketCreateUser',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9 ]+$')]),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='TransactionReqUser',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9 ]+$')]),
        ),
    ]
