# Generated by Django 2.1.10 on 2020-08-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='Time',
            field=models.TimeField(blank=True, default='15:43:13', null=True),
        ),
    ]
