# Generated by Django 2.1.10 on 2020-08-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0002_auto_20200824_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='Description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
