# Generated by Django 2.1.10 on 2020-08-07 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0002_auto_20200807_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonstocktransactionrecord',
            name='NonStockSpace',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='Time',
            field=models.TimeField(blank=True, default='16:35:58', null=True),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='NonStockNo',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-]+$')]),
        ),
    ]
