# Generated by Django 2.1.10 on 2020-08-10 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0003_auto_20200807_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolingcalibrationrecord',
            name='CalibratedEndTime',
        ),
        migrations.AddField(
            model_name='toolingcalibrationrecord',
            name='ActualCalibratedEndTime',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='toolingcalibrationrecord',
            name='ExpectedCalibratedEndTime',
            field=models.DateField(default='2020-08-24'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='Date',
            field=models.DateField(blank=True, default='2020-08-10', null=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='Time',
            field=models.TimeField(blank=True, default='10:39:57', null=True),
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='LoanEndTime',
            field=models.DateField(default='2021-02-10'),
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='LoanStartTime',
            field=models.DateField(default='2020-08-10'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='CreateDate',
            field=models.DateField(default='2020-08-10'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='LastModifyDate',
            field=models.DateField(default='2020-08-10'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='LastNonStockShipDate',
            field=models.DateField(blank=True, default='2020-08-10'),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='NonStockNo',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TicketCreateTime',
            field=models.DateField(default='2020-08-10'),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TransactionReqTime',
            field=models.DateField(default='2020-08-10'),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='CalibratedStartTime',
            field=models.DateField(default='2020-08-10'),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='CalibratedTicketCreateDate',
            field=models.DateField(default='2020-08-10'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='TicketCreateTime',
            field=models.DateField(default='2020-08-10'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='TransactionReqTime',
            field=models.DateField(default='2020-08-10'),
        ),
    ]
