# Generated by Django 2.1.10 on 2020-08-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0003_auto_20200824_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='EquipmentNo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
