# Generated by Django 2.1.10 on 2020-07-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0003_equipmentlist_moduleno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentlist',
            name='UnitPrice',
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='CalibratedCost',
            field=models.FloatField(blank=True),
        ),
    ]
