# Generated by Django 2.1.10 on 2020-08-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0004_transactionrecord_equipmentno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='PhotoLink',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
