# Generated by Django 2.1.10 on 2020-07-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0005_auto_20200728_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='CalibratedReport',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
