# Generated by Django 2.1.10 on 2020-08-24 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0005_auto_20200824_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionrecord',
            name='EquipmentNo',
        ),
    ]
