# Generated by Django 2.1.10 on 2020-07-28 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0006_auto_20200728_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolingcalibrationrecord',
            name='PhotoLink',
        ),
    ]
