# Generated by Django 2.1.10 on 2020-08-24 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0006_remove_transactionrecord_equipmentno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetloanrecord',
            name='AssetNo',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9- ]+$')]),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='AssetNo',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9- ]+$')]),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='EquipmentOwnerID',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9 ]+$')]),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='MaximoNo',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9- ]+$')]),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='ModuleNo',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\"\\/\\_\\-\\/ ]+$')]),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='ToolingNo',
            field=models.CharField(blank=True, default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9- ]+$')]),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='NonStockNo',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9- ]+$')]),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TicketCreateUser',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9 ]+$')]),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TransactionReqUser',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9 ]+$')]),
        ),
    ]
