# Generated by Django 2.1.10 on 2020-08-24 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0007_auto_20200824_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetloanrecord',
            name='EnName',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-\\*\\(\\)\\u3000\\u3400-\\u4DBF\\u4E00-\\u9FFF ]+$')]),
        ),
        migrations.AddField(
            model_name='assetloanrecord',
            name='Name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nonstocktransactionrecord',
            name='EnName',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-\\*\\(\\)\\u3000\\u3400-\\u4DBF\\u4E00-\\u9FFF ]+$')]),
        ),
        migrations.AddField(
            model_name='nonstocktransactionrecord',
            name='Name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='EnName',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-\\*\\(\\)\\u3000\\u3400-\\u4DBF\\u4E00-\\u9FFF ]+$')]),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='Name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='Name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='PhotoLink',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='EnName',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-\\*\\(\\)\\u3000\\u3400-\\u4DBF\\u4E00-\\u9FFF ]+$')]),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='Name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
