# Generated by Django 2.1.10 on 2020-07-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0008_toolingcalibrationrecord_photolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='CalibratedCost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
