# Generated by Django 2.1.10 on 2020-08-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0008_auto_20200824_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionrecord',
            name='EnName',
        ),
        migrations.RemoveField(
            model_name='transactionrecord',
            name='Name',
        ),
    ]
