# Generated by Django 2.1.10 on 2020-08-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0009_auto_20200824_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetQnty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(default=None, max_length=255)),
                ('Month', models.CharField(default=None, max_length=255)),
                ('Day', models.CharField(default=None, max_length=255)),
                ('Quantity', models.CharField(default=None, max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='NonStockQnty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(default=None, max_length=255)),
                ('Month', models.CharField(default=None, max_length=255)),
                ('Day', models.CharField(default=None, max_length=255)),
                ('Quantity', models.CharField(default=None, max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='ToolQnty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(default=None, max_length=255)),
                ('Month', models.CharField(default=None, max_length=255)),
                ('Day', models.CharField(default=None, max_length=255)),
                ('Quantity', models.CharField(default=None, max_length=4000)),
            ],
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='PhotoLink',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='PhotoLink',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
