# Generated by Django 2.1.10 on 2020-07-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0010_auto_20200728_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='Department',
            field=models.CharField(choices=[('TMC-1', 'TMC-1'), ('TMC-2', 'TMC-2'), ('PVD', 'PVD'), ('Operation', 'Operation')], default=('TMC-1', 'TMC-1'), max_length=255),
        ),
    ]
