# Generated by Django 2.1.10 on 2020-08-25 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0010_auto_20200824_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetqnty',
            name='Quantity',
            field=models.CharField(default=None, max_length=4000),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='EnName',
            field=models.CharField(default='', max_length=4000, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-\\*\\(\\)\\u3000\\u3400-\\u4DBF\\u4E00-\\u9FFF ]+$')]),
        ),
        migrations.AlterField(
            model_name='nonstockqnty',
            name='Quantity',
            field=models.CharField(default=None, max_length=4000),
        ),
        migrations.AlterField(
            model_name='toolqnty',
            name='Quantity',
            field=models.CharField(default=None, max_length=4000),
        ),
    ]
