# Generated by Django 2.1.10 on 2020-07-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0011_auto_20200728_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='Location',
            field=models.CharField(choices=[('CP', 'CP'), ('CVD-HC', 'CVD-HC'), ('CVD-LIC', 'CVD-LIC'), ('CVD-LID', 'CVD-LID'), ('PVD', 'PVD'), ('PVD-M', 'PVD-M'), ('PVD-IP', 'PVD-IP'), ('OLED-TEST', 'OLED-TEST')], default=('CP', 'CP'), max_length=255),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='Vendor',
            field=models.CharField(choices=[('GCH', 'GCH'), ('GCH/工研院', 'GCH/工研院'), ('GCH/工研院/內校', 'GCH/工研院/內校'), ('GCH/轉校', 'GCH/轉校'), ('MQ內校', 'MQ內校'), ('天熙科技/內校', '天熙科技/內校'), ('免校', '免校'), ('量測科技(MTC)', '量測科技(MTC)')], default=('GCH', 'GCH'), max_length=255),
        ),
    ]
