# Generated by Django 2.1.10 on 2020-08-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0011_auto_20200825_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentlist',
            name='ChDescription',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='EnDescription',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
    ]
