# Generated by Django 2.1.10 on 2020-08-27 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0012_auto_20200825_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentlist',
            name='DayUntilNextCalibration',
            field=models.IntegerField(default=180),
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='AssetLoanDocument',
            field=models.FileField(blank=True, upload_to='AssetLoanDocument'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='PhotoLink',
            field=models.ImageField(upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='CalibratedReport',
            field=models.FileField(blank=True, upload_to='CalibratedReport'),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='ToolingNo',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9- ]+$')]),
        ),
    ]
