# Generated by Django 2.1.10 on 2020-08-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0013_auto_20200827_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentlist',
            name='AssetLoanPeriod',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='DayUntilNextCalibration',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
