# Generated by Django 2.1.10 on 2020-08-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0014_auto_20200827_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentlist',
            name='AssetLoanPeriod',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='DayUntilNextCalibration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
