# Generated by Django 2.1.10 on 2020-07-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0014_delete_moduleno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetloanrecord',
            old_name='Cost',
            new_name='Value',
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='AssetLoanDocument',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='LoanReason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='LoanVendor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='Location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='PhotoLink',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='Location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='ModuleNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='Status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='TeamGroup',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='ToolingGroup',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TransactionFrom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TransactionTo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TruckType',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='AvgCalibratedPeriod',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='Location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='ModuleNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='Vendor',
            field=models.CharField(max_length=255),
        ),
    ]
