# Generated by Django 2.1.10 on 2020-08-27 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0015_auto_20200827_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentlist',
            name='AssetLoanPeriod',
        ),
        migrations.RemoveField(
            model_name='equipmentlist',
            name='DayUntilNextCalibration',
        ),
    ]
