# Generated by Django 2.1.10 on 2020-07-31 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0015_auto_20200730_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentlist',
            name='Status',
        ),
        migrations.AddField(
            model_name='toolingcalibrationrecord',
            name='AlertTime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolingcalibrationrecord',
            name='MQEndTIme',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolingcalibrationrecord',
            name='MQStartTime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolingcalibrationrecord',
            name='Status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='LoanStartTime',
            field=models.DateField(default='2020-07-31'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='CreateDate',
            field=models.DateField(default='2020-07-31'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='LastModifyDate',
            field=models.DateField(default='2020-07-31'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='LastNonStockShipDate',
            field=models.DateField(default='2020-07-31'),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TicketCreateTime',
            field=models.DateField(default='2020-07-31'),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TransactionReqTime',
            field=models.DateField(default='2020-07-31'),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='AvgCalibratedPeriod',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='CalibratedStartTime',
            field=models.DateField(default='2020-07-31'),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='CalibratedTicketCreateDate',
            field=models.DateField(default='2020-07-31'),
        ),
    ]
