# Generated by Django 2.1.10 on 2020-07-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0016_auto_20200731_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentlist',
            name='Status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
