# Generated by Django 2.1.10 on 2020-08-27 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0016_auto_20200827_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetloanrecord',
            name='EnName',
            field=models.CharField(default='', max_length=4000, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-\\*\\(\\)\\u3000\\u3400-\\u4DBF\\u4E00-\\u9FFF ]+$')]),
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='IsLongTermEvent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='LoanReason',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='Name',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='assetqnty',
            name='Quantity',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='Limitations',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='Name',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='Specification',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='nonstockqnty',
            name='Quantity',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='EnName',
            field=models.CharField(default='', max_length=4000, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-\\*\\(\\)\\u3000\\u3400-\\u4DBF\\u4E00-\\u9FFF ]+$')]),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='Name',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='OtherDemand',
            field=models.CharField(blank=True, default='', max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='Comment',
            field=models.CharField(blank=True, default='', max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='EnName',
            field=models.CharField(default='', max_length=4000, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-\\*\\(\\)\\u3000\\u3400-\\u4DBF\\u4E00-\\u9FFF ]+$')]),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='Name',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='toolqnty',
            name='Quantity',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='Description',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
