# Generated by Django 2.1.10 on 2020-07-31 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0017_auto_20200731_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolingcalibrationrecord',
            old_name='MQEndTIme',
            new_name='MQEndTime',
        ),
    ]
