# Generated by Django 2.1.10 on 2020-08-02 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0018_auto_20200731_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolingcalibrationrecord',
            name='EnName',
        ),
        migrations.RemoveField(
            model_name='toolingcalibrationrecord',
            name='ModuleNo',
        ),
        migrations.RemoveField(
            model_name='toolingcalibrationrecord',
            name='Name',
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='AssetNo',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='LoanStartTime',
            field=models.DateField(default='2020-08-02'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='AssetNo',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='CreateDate',
            field=models.DateField(default='2020-08-02'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='CreateUser',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$')]),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='EnName',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$')]),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='EquipmentOwnerID',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='EquipmentOwnerName',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$')]),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='LastModifyDate',
            field=models.DateField(default='2020-08-02'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='LastNonStockShipDate',
            field=models.DateField(default='2020-08-02'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='LimitFreezeQnty',
            field=models.IntegerField(default=1, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='ModuleNo',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\"\\/\\_\\-\\/]+$')]),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='NonStockNo',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='SerialNumber',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='ToolingNo',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='NonStockNo',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TicketCreateTime',
            field=models.DateField(default='2020-08-02'),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TicketCreateUser',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TransactionReqTime',
            field=models.DateField(default='2020-08-02'),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TransactionReqUser',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='CalibratedStartTime',
            field=models.DateField(default='2020-08-02'),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='CalibratedTicketCreateDate',
            field=models.DateField(default='2020-08-02'),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='ToolingNo',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
    ]
