# Generated by Django 2.1.10 on 2020-08-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0019_auto_20200802_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolingcalibrationrecord',
            name='EnName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='toolingcalibrationrecord',
            name='ModuleNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='toolingcalibrationrecord',
            name='Name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
