# Generated by Django 2.1.10 on 2020-08-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0020_auto_20200802_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.RemoveField(
            model_name='toolingcalibrationrecord',
            name='Vendor',
        ),
        migrations.AddField(
            model_name='equipmentlist',
            name='ProdVendor',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='toolingcalibrationrecord',
            name='CaliVendor',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='toolingcalibrationrecord',
            name='ProdVendor',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='LoanStartTime',
            field=models.DateField(default='2020-08-03'),
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='LoanVendor',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='Location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmentgroup',
            name='EquipmentGroupName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='CreateDate',
            field=models.DateField(default='2020-08-03'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='EquipmentGroup',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='LastModifyDate',
            field=models.DateField(default='2020-08-03'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='LastNonStockShipDate',
            field=models.DateField(default='2020-08-03'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='Location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='TeamGroup',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='ToolingGroup',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='Location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TicketCreateTime',
            field=models.DateField(default='2020-08-03'),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TransactionFrom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TransactionReqTime',
            field=models.DateField(default='2020-08-03'),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TransactionTo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TruckType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='Site',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='status',
            name='Status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='teamgroup',
            name='TeamGroupName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='CalibratedStartTime',
            field=models.DateField(default='2020-08-03'),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='CalibratedTicketCreateDate',
            field=models.DateField(default='2020-08-03'),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='Location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='toolinggroup',
            name='ToolingGroupName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='truck',
            name='Truck',
            field=models.CharField(default='', max_length=255),
        ),
    ]
