# Generated by Django 2.1.10 on 2020-08-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0021_auto_20200803_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
