# Generated by Django 2.1.10 on 2020-08-03 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0022_auto_20200803_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetloanrecord',
            name='LoanReason',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='ChDescription',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='Cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='CreateUser',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='EnDescription',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='EnName',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$')]),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='LastNonStockShipDate',
            field=models.DateField(blank=True, default='2020-08-03'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='Limitations',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='Specification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='Description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='OtherDemand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='Comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
