# Generated by Django 2.1.10 on 2020-08-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0023_auto_20200803_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentlist',
            name='NextCalibratedDate',
            field=models.DateField(blank=True, default='0001-08-03'),
        ),
    ]
