# Generated by Django 2.1.10 on 2020-08-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0024_auto_20200803_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonstocktransactionrecord',
            name='NonStockNo',
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='Value',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='NextCalibratedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
