# Generated by Django 2.1.10 on 2020-08-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0025_auto_20200803_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetloanrecord',
            name='Value',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='AvgCalibratedPeriod',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='UnitPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
