# Generated by Django 2.1.10 on 2020-08-04 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0026_auto_20200803_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolingcalibrationrecord',
            name='Status',
        ),
        migrations.AddField(
            model_name='nonstocktransactionrecord',
            name='NonStockNo',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='LoanStartTime',
            field=models.DateField(default='2020-08-04'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='CreateDate',
            field=models.DateField(default='2020-08-04'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='LastModifyDate',
            field=models.DateField(default='2020-08-04'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='LastNonStockShipDate',
            field=models.DateField(blank=True, default='2020-08-04'),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TicketCreateTime',
            field=models.DateField(default='2020-08-04'),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TransactionReqTime',
            field=models.DateField(default='2020-08-04'),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='CalibratedStartTime',
            field=models.DateField(default='2020-08-04'),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='CalibratedTicketCreateDate',
            field=models.DateField(default='2020-08-04'),
        ),
    ]
