# Generated by Django 2.1.10 on 2020-08-04 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0027_auto_20200804_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('TicketNo', models.AutoField(primary_key=True, serialize=False)),
                ('TransactionTicketNo', models.CharField(default='', max_length=255)),
                ('TransactionNo', models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9]+$')])),
                ('EquipmentNo', models.CharField(default='', max_length=255)),
                ('TicketCreateTime', models.DateField(default='2020-08-04')),
                ('TicketCreateUser', models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$')])),
                ('TransactionReqTime', models.DateField(default='2020-08-04')),
                ('TransactionReqUser', models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$')])),
                ('TransactionFrom', models.CharField(default='', max_length=255)),
                ('TransactionTo', models.CharField(default='', max_length=255)),
                ('TruckType', models.CharField(default='', max_length=255)),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
                ('OtherDemand', models.CharField(blank=True, max_length=255, null=True)),
                ('Deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='NonStockNo',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
    ]
