# Generated by Django 2.1.10 on 2020-08-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0028_auto_20200804_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionrecord',
            name='EquipmentNo',
        ),
        migrations.RemoveField(
            model_name='transactionrecord',
            name='OtherDemand',
        ),
        migrations.RemoveField(
            model_name='transactionrecord',
            name='TransactionNo',
        ),
        migrations.AlterField(
            model_name='assetloanrecord',
            name='LoanStartTime',
            field=models.DateField(default='2020-08-05'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='CreateDate',
            field=models.DateField(default='2020-08-05'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='LastModifyDate',
            field=models.DateField(default='2020-08-05'),
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='LastNonStockShipDate',
            field=models.DateField(blank=True, default='2020-08-05'),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TicketCreateTime',
            field=models.DateField(default='2020-08-05'),
        ),
        migrations.AlterField(
            model_name='nonstocktransactionrecord',
            name='TransactionReqTime',
            field=models.DateField(default='2020-08-05'),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='CalibratedStartTime',
            field=models.DateField(default='2020-08-05'),
        ),
        migrations.AlterField(
            model_name='toolingcalibrationrecord',
            name='CalibratedTicketCreateDate',
            field=models.DateField(default='2020-08-05'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='TicketCreateTime',
            field=models.DateField(default='2020-08-05'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='TransactionReqTime',
            field=models.DateField(default='2020-08-05'),
        ),
    ]
