# Generated by Django 2.1.10 on 2020-08-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0029_auto_20200805_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetloanrecord',
            name='IsLongTermEvent',
            field=models.BooleanField(default=True),
        ),
    ]
