# Generated by Django 2.1.10 on 2020-08-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0030_auto_20200805_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentlist',
            name='TransactionTicketNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
